ROBERTA_CLASSIFIER = {
    "LEARNING_RATE": 2e-5,
    "DROPOUT": 0.1,
    "ENCODER": "CLS",
    "NUM_FEEDFORWARD_LAYERS": 1,
    "FEEDFORWARD_WIDTH_MULTIPLIER": 1,
    "EMBEDDING": "ROBERTA",
    "NUM_EPOCHS": 10,
    "PATIENCE": 3,
    "NUM_GRAD_ACC_STEPS": 1,
    "BATCH_SIZE": 16,
}

ROBERTA_CLASSIFIER_BIG = {
    "LEARNING_RATE": 2e-5,
    "DROPOUT": 0.1,
    "ENCODER": "CLS",
    "NUM_FEEDFORWARD_LAYERS": 1,
    "FEEDFORWARD_WIDTH_MULTIPLIER": 1,
    "EMBEDDING": "ROBERTA",
    "NUM_EPOCHS": 3,
    "PATIENCE": 3,
    "NUM_GRAD_ACC_STEPS": 2,
    "BATCH_SIZE": 16,
}

ROBERTA_TAGGER = {
    "LEARNING_RATE": 5e-5,
    "DROPOUT": 0.1,
    "ENCODER": "CLS",
    "NUM_FEEDFORWARD_LAYERS": 1,
    "FEEDFORWARD_WIDTH_MULTIPLIER": 1,
    "EMBEDDING": "ROBERTA",
    "NUM_EPOCHS": 5,
    "PATIENCE": 3,
    "NUM_GRAD_ACC_STEPS": 2,
    "BATCH_SIZE": 16,
}

HYPERPARAMETERS = {
    "ROBERTA_CLASSIFIER": ROBERTA_CLASSIFIER,
    "ROBERTA_TAGGER": ROBERTA_TAGGER,
    "ROBERTA_CLASSIFIER_BIG": ROBERTA_CLASSIFIER_BIG
}
